name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "^1.15.0"
          - "^1.14.0"
          - "^1.13.0"
          - "^1.12.0"
          - "^1.11.0"
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.perl }}
      - run: go test -race -coverprofile=coverage.out -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
